### ISSUE TITLE
好像激活失败 证书过期了把

### ISSUE THREAD

**Issue by ring007c** [akkuman/docker-awvs#1]
{
  "status": "failed",
  "scanning_app": "wvs",
  "extended_status": {
    "attachments": [
      {
        "url": "file:///home/acunetix/.acunetix/data/scans/669b02d2-be1a-4f42-bbc4-2f20643a6e67.zip",
        "name": "output"
      }
    ],
    "fail_reason": {
      "stderr": "WVSC Reactivation Failed",
      "message": "License problem",
      "exit_code": 40
    }
  }
}

**Comment by akkuman** [comment]
已修正，使用 `docker compose pull` 更新镜像，然后再启动看看
